# Generated by Django 5.0.4 on 2024-05-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=30, unique=True)),
                ('add_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=30)),
                ('emp_emailid', models.EmailField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('emp_skills', models.CharField(max_length=250)),
                ('emp_pwd', models.CharField(max_length=250)),
                ('emp_phone', models.CharField(max_length=10)),
                ('add_date', models.DateField(auto_now=True)),
                ('pay_sts', models.BooleanField(default=False)),
                ('Status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='Active', max_length=10)),
                ('likes', models.IntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.department')),
                ('emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.role')),
            ],
        ),
    ]
