# Generated by Django 5.0.4 on 2024-05-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblleaves',
            name='emp_emailid',
            field=models.ForeignKey(blank=True, db_column='emp_emailid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='happyPerformerBackend.employee'),
        ),
        migrations.AlterField(
            model_name='tblleaves',
            name='LeaveType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.leavetype'),
        ),
    ]
