# Generated by Django 5.0.4 on 2024-05-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
