# Generated by Django 5.0.4 on 2024-05-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_emailid',
            field=models.EmailField(default='A@gmail.com', max_length=50, primary_key=True, serialize=False),
        ),
    ]
