# Generated by Django 5.0.4 on 2024-05-30 19:41

import happyPerformerBackend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhaar',
            name='adhaar_pic',
            field=models.FileField(upload_to='adhaar_pics/', validators=[happyPerformerBackend.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='adhaar',
            name='enroll_no',
            field=models.PositiveBigIntegerField(),
        ),
    ]
