# Generated by Django 5.0.4 on 2024-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0002_alter_reporting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expensedate',
            field=models.DateField(max_length=15),
        ),
    ]
