# Generated by Django 5.0.4 on 2024-06-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0002_alter_pan_pan_pic_alter_passport_passport_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearance',
            name='emp_emailid',
        ),
        migrations.AddField(
            model_name='clearance',
            name='given_to',
            field=models.ForeignKey(db_column='given_to', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clearnaces_to', to='happyPerformerBackend.employee'),
        ),
    ]
