# Generated by Django 5.0.4 on 2024-05-20 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0002_tblleaves_emp_emailid_alter_tblleaves_leavetype'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='video',
            new_name='happyPerfor_course__d4aeea_idx',
            old_name='happyPerfor_course__8af725_idx',
        ),
        migrations.AlterField(
            model_name='video',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.courses'),
        ),
    ]
