# Generated by Django 5.0.4 on 2024-05-23 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0002_alter_employee_emp_emailid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='case',
            name='case_created_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='case_assigned_to_idx',
        ),
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(db_column='emp_emailid', on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to='happyPerformerBackend.employee'),
        ),
    ]
