# Generated by Django 5.0.4 on 2024-05-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0003_alter_expenses_expensedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblleaves',
            name='emp_emailid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
