# Generated by Django 5.0.4 on 2024-05-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0003_rename_happyperfor_course__8af725_idx_happyperfor_course__d4aeea_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employee_d_id',
        ),
    ]
