# Generated by Django 5.0.4 on 2024-05-23 06:35

import happyPerformerBackend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0003_remove_case_case_created_by_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/', validators=[happyPerformerBackend.validators.validate_image_extension]),
        ),
    ]
