# Generated by Django 5.0.4 on 2024-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0003_remove_clearance_emp_emailid_clearance_given_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_forms',
            name='alloc',
            field=models.TextField(default=None, max_length=250, null=True),
        ),
    ]
