# Generated by Django 5.0.4 on 2024-05-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0004_remove_employee_employee_d_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblleaves',
            name='emp_emailid',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
