# Generated by Django 5.0.4 on 2024-05-23 07:28

import happyPerformerBackend.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0004_alter_courses_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_profile',
            field=models.ImageField(default='profile.png', upload_to='profile/', validators=[happyPerformerBackend.validators.validate_image_extension]),
        ),
    ]
