# Generated by Django 5.0.4 on 2024-05-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0004_alter_tblleaves_emp_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblleaves',
            name='LeaveType',
            field=models.ForeignKey(db_column='LeaveType', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.leavetype'),
        ),
        migrations.AlterField(
            model_name='tblleaves',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
