# Generated by Django 5.0.4 on 2024-05-20 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0005_alter_tblleaves_emp_emailid'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clearance',
            name='clearance_employee_idx',
        ),
        migrations.RemoveIndex(
            model_name='clearance',
            name='clearance_given_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='custom_letters',
            name='custom_letters_lname_c_id',
        ),
        migrations.RemoveIndex(
            model_name='custom_letters',
            name='custom_letters_c_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='dependent',
            name='happyPerfor_P_Id_f21c3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='family_details',
            name='family_details_P_Id',
        ),
        migrations.RemoveIndex(
            model_name='itdeclaration80d_new',
            name='itdeclaration80d_new_Emp_id',
        ),
        migrations.RemoveIndex(
            model_name='itdeclaration_oie_new',
            name='itdeclaration_oie_new_Emp_id',
        ),
        migrations.RemoveIndex(
            model_name='job_info',
            name='job_info_P_Id_idx',
        ),
        migrations.RemoveIndex(
            model_name='leave_encashment',
            name='leave_encashment_emp_idx',
        ),
        migrations.RemoveIndex(
            model_name='licence',
            name='happyPerfor_P_Id_5a52d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='pan',
            name='happyPerfor_P_Id_9ce85c_idx',
        ),
        migrations.RemoveIndex(
            model_name='passport',
            name='happyPerfor_P_Id_834938_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualification',
            name='happyPerfor_emp_ema_db0634_idx',
        ),
        migrations.RemoveIndex(
            model_name='resignation',
            name='happyPerfor_emp_ema_cd6729_idx',
        ),
        migrations.RemoveIndex(
            model_name='sop',
            name='happyPerfor_d_id_93f7a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='work_exp',
            name='happyPerfor_emp_ema_6da573_idx',
        ),
        migrations.RenameField(
            model_name='work_exp',
            old_name='P_Id',
            new_name='emp_emailid',
        ),
        migrations.RemoveField(
            model_name='adhaar',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='bank_details',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='clearance',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='family_details',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='itdeclaration80d_new',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itdeclaration_oie_new',
            name='id',
        ),
        migrations.RemoveField(
            model_name='itdeclaration_osi_new',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job_info',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='pan',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='P_Id',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='P_Id',
        ),
        migrations.AddField(
            model_name='adhaar',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='bank_details',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='clearance',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='family_details',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='itdeclaration80d_new',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='itdeclaration_oie_new',
            name='emp_emaiid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='itdeclaration_osi_new',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='job_info',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='licence',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='pan',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='passport',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AddField(
            model_name='resignation',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AlterField(
            model_name='forms',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AlterField(
            model_name='itdeclaration80d_new',
            name='Emp_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itdeclaration_oie_new',
            name='Emp_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itdeclaration_osi_new',
            name='Emp_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='mail',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AlterField(
            model_name='poifiles_new',
            name='Emp_id',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
