# Generated by Django 5.0.4 on 2024-08-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0005_alter_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
    ]
