# Generated by Django 5.0.4 on 2024-05-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0005_alter_tblleaves_leavetype_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kra',
            name='kra_kra_id_idx',
        ),
        migrations.AlterField(
            model_name='leavecounttemp',
            name='emp_emailid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
