# Generated by Django 5.0.4 on 2024-05-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0005_alter_employee_emp_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='course_id',
        ),
        migrations.AddField(
            model_name='pdf',
            name='course',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.courses'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='descr',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_name',
            field=models.CharField(max_length=255),
        ),
    ]
