# Generated by Django 5.0.4 on 2024-05-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0006_remove_pdf_course_id_pdf_course_alter_pdf_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.courses'),
        ),
    ]
