# Generated by Django 5.0.4 on 2024-05-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0006_remove_clearance_clearance_employee_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_case_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatbot_categories',
            name='chatbot_categories_c_id_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatbot_questions',
            name='chatbot_questions_category',
        ),
        migrations.RemoveIndex(
            model_name='custom_forms',
            name='custom_forms',
        ),
        migrations.RemoveIndex(
            model_name='custom_forms_questions',
            name='custom_forms_questions',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='department_d_name_c_id',
        ),
        migrations.RemoveIndex(
            model_name='department',
            name='department_c_id',
        ),
        migrations.RemoveField(
            model_name='course_employee',
            name='Email_id',
        ),
        migrations.AddField(
            model_name='course_employee',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
        migrations.AlterField(
            model_name='course_employee',
            name='course_title',
            field=models.ForeignKey(db_column='course_title', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='c_id',
            field=models.ForeignKey(db_column='c_id', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.company'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='c_name',
            field=models.CharField(max_length=30),
        ),
    ]
