# Generated by Django 5.0.4 on 2024-08-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0006_quiz_marks_obtained'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='marks_obtained',
            new_name='total_marks',
        ),
    ]
