# Generated by Django 5.0.4 on 2024-05-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0007_alter_pdf_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(default=81, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='happyPerformerBackend.company'),
        ),
    ]
