# Generated by Django 5.0.4 on 2024-05-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0007_remove_chat_chat_case_id_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_employee',
            old_name='course_title',
            new_name='course_id',
        ),
    ]
