# Generated by Django 5.0.4 on 2024-08-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0008_alter_employee_emp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_pwd',
            field=models.CharField(default='changeme', max_length=50),
        ),
    ]
