# Generated by Django 5.0.4 on 2024-05-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0008_rename_course_title_course_employee_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_employee',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.courses'),
        ),
    ]
