# Generated by Django 5.0.4 on 2024-05-24 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0009_alter_leavetype_company'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='faqs',
            name='faqs_emp_emailid',
        ),
        migrations.RemoveIndex(
            model_name='faqs',
            name='faqs_c_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='Email_id',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.courses'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='email_id',
            field=models.ForeignKey(default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
