# Generated by Django 5.0.4 on 2024-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0009_alter_employee_emp_phone_alter_employee_emp_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_emailid',
            field=models.EmailField(default='A@gmail.com', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_role',
            field=models.CharField(max_length=100),
        ),
    ]
