# Generated by Django 5.0.4 on 2024-05-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0009_alter_course_employee_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_employee',
            name='course_title',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
