# Generated by Django 5.0.4 on 2024-05-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0010_remove_faqs_faqs_emp_emailid_remove_faqs_faqs_c_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='email_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
