# Generated by Django 5.0.4 on 2024-08-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0010_alter_employee_emp_emailid_alter_employee_emp_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_pwd',
            field=models.CharField(default='changeme', max_length=100),
        ),
    ]
