# Generated by Django 5.0.4 on 2024-08-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0011_alter_employee_emp_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='log_type',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
