# Generated by Django 5.0.4 on 2024-05-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0011_alter_certificate_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_employee',
            name='course_id',
            field=models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.courses'),
        ),
        migrations.AlterField(
            model_name='course_employee',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
