# Generated by Django 5.0.4 on 2024-05-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0012_alter_course_employee_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='id',
        ),
        migrations.AddField(
            model_name='salary',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.bank_details'),
        ),
    ]
