# Generated by Django 5.0.4 on 2024-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0013_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='log_type',
            field=models.CharField(blank=True, default='Unknown', max_length=10, null=True),
        ),
    ]
