# Generated by Django 5.0.4 on 2024-05-25 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0013_remove_salary_id_salary_emp_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee', unique=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.bank_details', to_field='emp_emailid'),
        ),
    ]
