# Generated by Django 5.0.4 on 2024-08-31 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0014_alter_attendance_log_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='emp_emailid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
