# Generated by Django 5.0.4 on 2024-05-26 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0014_alter_bank_details_emp_emailid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to='happyPerformerBackend.employee'),
        ),
    ]
