# Generated by Django 5.0.4 on 2024-05-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0015_alter_case_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='amt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='adhoc',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
