# Generated by Django 5.0.4 on 2024-05-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0016_alter_adhoc_amt_alter_adhoc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='lamt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='mamt',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
