# Generated by Django 5.0.4 on 2024-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0016_alter_tblleaves_adminremarkdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='office_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
