# Generated by Django 5.0.4 on 2024-05-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0017_alter_loan_lamt_alter_loan_mamt_alter_loan_reason_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leave_encashment',
            new_name='LeaveEncashment',
        ),
    ]
