# Generated by Django 5.0.4 on 2024-05-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0018_rename_leave_encashment_leaveencashment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveEncashment',
            new_name='Leave_Encashment',
        ),
    ]
