# Generated by Django 5.0.4 on 2024-05-27 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0019_rename_leaveencashment_leave_encashment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_encashment',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default=None, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
