# Generated by Django 5.0.4 on 2024-05-27 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0021_alter_leave_encashment_emp_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_encashment',
            name='emp_emailid',
            field=models.ForeignKey(db_column='emp_emailid', default='abc@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee'),
        ),
    ]
